services:
  handbreak:
    image: jlesage/handbrake:latest
    container_name: handbreak
    environment:
      - USER_ID=568
      - GROUP_ID=568
      - TZ=Europe/Berlin
      - KEEP_APP_RUNNING=1
      - DARK_MODE=1
      - WEB_LISTENING_PORT=10053
      - VNC_LISTENING_PORT=-1 # Disable, if needed put the port wanted, and change in the ports section
      - VNC_PASSWORD=password # CHANGE ME
      - AUTOMATED_CONVERSION=0
    ports:
      - 10053:10053 # handbreak WEB
      # - 10056:10056 # handbreak VNC
    volumes:
      - /mnt/HANDBREAK_DIR:/config  # This is where the application stores its configuration, states, log and any files needing persistency. # CHANGE ME
      - /mnt/MEDIA_DIR:/storage:ro  # This location contains files from your host that need to be accessible to the application. # CHANGE ME
      - /mnt/HANDBREAK_OUT:/output  # This is where automatically converted video files are written. # CHANGE ME
    deploy:
      resources:
        limits:
          cpus: "24"
          memory: "8g"
    restart: unless-stopped