services:
  deezspot_bot:
    image: j0n4n/deezspot_bot_docker:latest
    container_name: deezspot_bot
    environment:
      - USER_ERRORS=CHAT_ID_ERRORS # Chat id where to send users errors. # CHANGE ME
      - BUNKER_CHANNEL=BUNKER_CHANNEL_ID # Chat id to use as an archive # CHANGE ME
      - OWL_CHANNEL=OWL_CHANNEL_ID # Chat id where to listen for announcements to the users # CHANGE ME
      - ROOT_ID=ROOT_USER_ID # User id to have admin access # CHANGE ME
      - BOT_NAME="BOT_NAME" # Username with the @ of the bot. # CHANGE ME
      - ARL_TOKEN=DEEZER_ARL_TOKEN # Deezer ARL token # CHANGE ME
      - EMAIL_DEE=DEEZER_EMAIL # Email to log in on Deezer # CHANGE ME
      - PWD_DEE=DEEZER_PASSWORD # Password to log in on Deezer # CHANGE ME
      - BOT_TOKEN=TELEGRAM_BOT_TOKEN # Telegram bot token # CHANGE ME
      - API_ID=TELEGRAM_API_ID # Telegram api id # CHANGE ME
      - API_HASH=TELEGRAM_API_HASH # Telegram api hash # CHANGE ME
      - TZ=Europe/Berlin
    volumes:
      - /mnt/DB_DIR:/app/DB # CHANGE ME
      - /mnt/CREDENTIALS_DIR:/app/credentials # CHANGE ME
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "8g"
    restart: unless-stopped