name: Build Unattended Kali ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends wget p7zip-full

      - name: Download latest Kali ISO
        run: |
          ISO_FILENAME=$(curl -sL https://cdimage.kali.org/current/ | grep -Eo 'kali-linux-.*-installer-amd64\.iso"' | head -n 1 | cut -d'"' -f1)
          ISO_URL="https://cdimage.kali.org/current/${ISO_FILENAME}"
          
          echo "ISO_FILENAME=${ISO_FILENAME}" >> $GITHUB_ENV
          echo "ISO_URL=${ISO_URL}" >> $GITHUB_ENV
          
          echo "Downloading from ${ISO_URL}"
          wget -q --show-progress -O "${ISO_FILENAME}" "${ISO_URL}"

      - name: Extract ISO contents
        run: |
          mkdir -p /tmp/kaliISO
          7z x ${{ env.ISO_FILENAME }} -o/tmp/kaliISO

      - name: Append boot entry
        run: |
          curl -sL https://raw.githubusercontent.com/J0nan/RandomThings/refs/heads/main/provisioning/kali/generic/txt.cfg | sudo tee -a /tmp/kaliISO/isolinux/txt.cfg

      - name: Rebuild the ISO image
        run: |
          ORIGINAL_NAME="${ISO_FILENAME%.iso}"
          UNATTENDED_ISO_NAME="${ORIGINAL_NAME}_unattended-J0nan.iso"
          echo "UNATTENDED_ISO_NAME=${UNATTENDED_ISO_NAME}" >> $GITHUB_ENV

          sudo mkisofs -D -r -V "UNATTENDED_KALI" \
            -cache-inodes -J -l -b isolinux/isolinux.bin \
            -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 \
            -boot-info-table -o "${UNATTENDED_ISO_NAME}" /tmp/kaliISO

      - name: Create GitHub Release and Upload ISO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          KALI_VERSION=$(echo "${{ env.ISO_FILENAME }}" | grep -oP '\d{4}\.\d+')
          RELEASE_TAG="v${KALI_VERSION}"

          echo "Creating GitHub release with tag ${RELEASE_TAG}"
          
          gh release create "${RELEASE_TAG}" \
            "${{ env.UNATTENDED_ISO_NAME }}" \
            --title "Kali Unattended ${KALI_VERSION}" \
            --notes "This release contains an automated, unattended installer for Kali Linux version ${KALI_VERSION}."